routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Front')->name('front.')->group(function()
{
	Route::get('/','HomeController@index')->name('get.home.index');
	Route::post('/loadMore','HomeController@loadMore')->name('get.home.loadMore');

	Route::get('/properties','PropertyController@index')->name('get.property.index');
	Route::get('/properties/sell','PropertyController@sell')->name('get.property.sell');
	Route::get('/properties/rent','PropertyController@rent')->name('get.property.rent');
	Route::get('/properties/place/{slug}','PropertyController@place')->name('get.property.place');
	
	Route::post('/properties/search','PropertyController@doSearch')->name('post.property.doSearch');
	Route::get('/properties/{slug}','PropertyController@show')->name('get.property.show');

	Route::get('/agents','AgentController@index')->name('get.agent.index');
	Route::get('/agents/profile/{slug}','AgentController@profile')->name('get.agent.profile');
	Route::post('/agents/message','AgentController@sendMessage')->name('post.agent.sendMessage');

	Route::get('/about', 'AboutController@index')->name('get.about.index');

	Route::get('/contact', 'ContactController@index')->name('get.contact.index');
	Route::post('/contact', 'ContactController@sendMessage')->name('post.contact.sendMessage');

	Route::post('/subscribe', 'HomeController@subscribe')->name('post.home.subscribe');
});

app/Http/Controllers/Front/AboutController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\About;
use App\Models\Agent;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AboutController extends Controller
{
    public function index()
    {
        $data['about'] = About::first();
        $data['agents'] = Agent::select('name', 'slug', 'img', 'email', 'phone')
        ->where('show_in_homepage', 'yes')
        ->get();        
        
        return view('front.about.index')->with($data);
    }
}

app/Http/Controllers/Front/AgentController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Agent;
use App\Models\AgentRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\AgentRequestRequest;

class AgentController extends Controller
{
    public function index()
    {
        $data['agents'] = Agent::select('name', 'slug', 'pos', 'small_desc', 'img', 'email', 'phone', 'facebook', 'linkedin')
        ->where('show', 'yes')
        ->get();
        
        return view('front.agents.index')->with($data);
    }

    public function profile($slug)
    {
        $data['agent'] = Agent::where('slug', $slug)->first();

        return view('front.agents.profile')->with($data);
    }

    public function sendMessage(AgentRequestRequest $request)
    {
        if($request->ajax())
        {
            $data = $request->validated();
            AgentRequest::create($data);
            $message['success'] = trans('Message sent successfully');
            return response()->json($message);
        }
    }
}

app/Http/Controllers/Front/ContactController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Message;
use App\Models\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\MessageRequest;

class ContactController extends Controller
{
    public function index()
    {
        $data['contacts'] = Setting::select('email', 'mobile', 'linkedin', 'facebook', 'business_hours')
        ->first();
        return view('front.contact.index')->with($data);
    }

    public function sendMessage(MessageRequest $request)
    {
        if($request->ajax())
        {
            $data = $request->validated();
            Message::create($data);
            $message['success'] = trans('Message sent successfully');
            return response()->json($message);
        }
    }
}

app/Http/Controllers/Front/HomeController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Requests\SubscribeRequest;
use App\Http\Requests\LoadMoreRequest;
use App\Http\Controllers\Controller;
use App\Models\Slider;
use App\Models\Place;
use App\Models\Agent;
use App\Models\Prop;
use App\Models\Setting;
use App\Models\Subscribe;
use App\Models\Offer;
use View;

class HomeController extends Controller
{
    public function index()
    {
        $data['sliders'] = Slider::select('name', 'img', 'price', 'link')
        ->where('show', 'yes')
        ->get();

        $data['offers'] = Offer::select('name', 'sub_title', 'img', 'link')
        ->where('show_in_homepage', 'yes')
        ->get();

        $data['agents'] = Agent::select('name', 'slug', 'img', 'email', 'phone')
        ->where('show_in_homepage', 'yes')
        ->get();

        $data['places'] = Place::select('id', 'name', 'img', 'slug')
        ->where('show_in_homepage', 'yes')
        ->limit(6)
        ->get();

        $data['props'] = Prop::select('type', 'price', 'place_id', 'img', 'slug', 'beds', 'baths', 'lot_size')
        ->where('show_in_homepage', 'yes')
        ->limit(9)
        ->get();

        return view('front.index')->with($data);
    }

    public function loadMore(LoadMoreRequest $request)
    {
        if($request->ajax())
        {
            $data = $request->validated();

            if($data['num'] == 3) 
            {
                $data['props_two'] = Prop::select('type', 'price', 'place_id', 'img', 'slug', 'beds', 'baths', 'lot_size')
                ->where('show_in_homepage', 'yes')->skip(3)->take(3)->get();
                
                $view = View::make('front.render.propTwo', $data);
            }
            else if($data['num'] == 6) 
            {
                $data['props_three'] = Prop::select('type', 'price', 'place_id', 'img', 'slug', 'beds', 'baths', 'lot_size')
                ->where('show_in_homepage', 'yes')->skip(6)->take(3)->get();
                
                $view = View::make('front.render.propThree', $data);
            }
            

            $html = $view->render();
            
            return response()->json($html);
        }
    }

    public function subscribe(SubscribeRequest $request)
    {
        if($request->ajax())
        {
            $data = $request->validated();
            Subscribe::create($data);
            $message['success'] = trans('Subscribed successfully');
            return response()->json($message);
        }
    }
}

app/Http/Controllers/Front/PropertyController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Prop;
use App\Models\Agent;
use App\Models\Place;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\SearchRequest;

class PropertyController extends Controller
{
    public function index(SearchRequest $request)
    {
        $params = $request->validated();

        if($params !== [])
        {
            $data['status'] = 'search';
            $data['search'] = true;
            $data['params'] = $params;

            $props = Prop::when($params['cat'] !== null, function ($props) {
                    return $props->where('category_id', request('cat'));
                })
                ->when($params['place'] !== null, function ($props) {
                    return $props->where('place_id', request('place'));
                })
                ->when($params['type'] !== null, function ($props) {
                    return $props->where('type', request('type'));
                })
                ->when($params['min_price'] !== null, function ($props) {
                    return $props->where('price', '>=', request('min_price'));
                })
                ->when($params['max_price'] !== null, function ($props) {
                    return $props->where('price', '<=', request('max_price'));
                });

            $data['props'] = $props->paginate(6);
        } else {
            $data['status'] = 'all';
            $data['props'] = Prop::paginate(6);
        }

        
        return view('front.properties.index')->with($data);
    }

    public function sell()
    {
        $data['props'] = Prop::where('type', 'sell')->paginate(6);
        $data['count'] = count(Prop::where('type', 'sell')->get());
        $data['status'] = 'sell';

        return view('front.properties.index')->with($data);
    }

    public function rent()
    {
        $data['props'] = Prop::where('type', 'rent')->paginate(6);
        $data['count'] = count(Prop::where('type', 'rent')->get());
        $data['status'] = 'rent';

        return view('front.properties.index')->with($data);
    }

    public function place($slug)
    {
        $place = Place::where('slug', $slug)->first();
        $data['place'] = $place;
        $data['props'] = Prop::where('place_id', $place->id)->paginate(6);
        $data['count'] = count(Prop::where('type', 'rent')->get());
        $data['status'] = 'place';

        return view('front.properties.index')->with($data);
    }


    public function show($slug)
    {
        $data['prop'] = Prop::where('slug', $slug)->first();
        return view('front.properties.show')->with($data);
    }
}

resources/views/front/inc/footer.blade.php
<footer id="footer" class="m-0 custom-bg-color-1 py-4">
    <div class="container">
        <div class="row pt-5 pb-4">
            <div class="col-md-4 col-lg-3">
                <h4 class="mb-3">Porto Real Estate</h4>
                <p class="custom-color-2 mb-0">
                    {{ $settings->address }}<br>
                    Phone : {{ $settings->phone }}<br>
                    Email : <a class="text-color-secondary" href="mailto:mail@example.com">{{ $settings->email }}</a>
                </p>
            </div>
            <div class="col-md-2">
                <h4 class="mb-3">Properties</h4>
                <nav class="nav-footer">
                    <ul class="custom-list-style-1 mb-0">
                        <li>
                            <a href="{{ route('front.get.property.sell') }}" class="custom-color-2 text-decoration-none">
                                For Sale
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('front.get.property.rent') }}" class="custom-color-2 text-decoration-none">
                                For Rent
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-md-2">
                <h4 class="mb-3">Links</h4>
                <nav class="nav-footer">
                    <ul class="custom-list-style-1 mb-0">
                        <li>
                            <a href="{{ route('front.get.agent.index') }}" class="custom-color-2 text-decoration-none">
                                Agents
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('front.get.about.index') }}" class="custom-color-2 text-decoration-none">
                                Who We Are
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('front.get.contact.index') }}" class="custom-color-2 text-decoration-none">
                                Contact
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-md-4 col-lg-5">
                <h4 class="mb-3">Latest Tweet</h4>
                <div id="tweet" class="twitter" data-plugin-tweets data-plugin-options="{'username': 'oklerthemes', 'count': 1}">
                    <p>Please wait...</p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-copyright custom-bg-color-1 pb-0">
        <div class="container">
            <div class="row pt-3 pb-4">
                <div class="col-lg-12 left m-0 pb-3">
                    <p>© Copyright EraaSoft 2019. All Rights Reserved.</p>
                </div>
            </div>
        </div>
    </div>
</footer>
</div>
</div>

<!-- Vendor -->
<script src="{{ furl() }}/assets/vendor/jquery/jquery.min.js"></script>		
<script src="{{ furl() }}/assets/vendor/jquery.appear/jquery.appear.min.js"></script>
<script src="{{ furl() }}/assets/vendor/jquery.easing/jquery.easing.min.js"></script>		
<script src="{{ furl() }}/assets/vendor/jquery.cookie/jquery.cookie.min.js"></script>		
<script src="{{ furl() }}/assets/master/style-switcher/style.switcher.js" id="styleSwitcherScript" data-base-path="" data-skin-src="master/less/skin-real-estate.less"></script>		
<script src="{{ furl() }}/assets/vendor/popper/umd/popper.min.js"></script>		
<script src="{{ furl() }}/assets/vendor/bootstrap/js/bootstrap.min.js"></script>		
<script src="{{ furl() }}/assets/vendor/common/common.min.js"></script>		
<script src="{{ furl() }}/assets/vendor/jquery.validation/jquery.validate.min.js"></script>		
<script src="{{ furl() }}/assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>		
<script src="{{ furl() }}/assets/vendor/jquery.gmap/jquery.gmap.min.js"></script>		
<script src="{{ furl() }}/assets/vendor/jquery.lazyload/jquery.lazyload.min.js"></script>		
<script src="{{ furl() }}/assets/vendor/isotope/jquery.isotope.min.js"></script>		
<script src="{{ furl() }}/assets/vendor/owl.carousel/owl.carousel.min.js"></script>		
<script src="{{ furl() }}/assets/vendor/magnific-popup/jquery.magnific-popup.min.js"></script>		
<script src="{{ furl() }}/assets/vendor/vide/jquery.vide.min.js"></script>

<!-- Theme Base, Components and Settings -->
<script src="{{ furl() }}/assets/js/theme.js"></script>

<!-- Current Page Vendor and Views -->
<script src="{{ furl() }}/assets/vendor/rs-plugin/js/jquery.themepunch.tools.min.js"></script>		
<script src="{{ furl() }}/assets/vendor/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>

<!-- Current Page Vendor and Views -->
<script src="{{ furl() }}/assets/js/views/view.contact.js"></script>

<!-- Demo -->
<script src="{{ furl() }}/assets/js/demos/demo-real-estate.js"></script>

<!-- Theme Custom -->
<script src="{{ furl() }}/assets/js/custom.js"></script>

<!-- Theme Initialization Files -->
<script src="{{ furl() }}/assets/js/theme.init.js"></script>

<script src="{{ furl() }}/assets/js/main.js"></script>



<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','../../../www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-42715764-5', 'auto');
    ga('send', 'pageview');
</script>

<script src="{{ furl() }}/assets/master/analytics/analytics.js"></script>


@yield('scripts')

</body>

<!-- Mirrored from preview.oklerthemes.com/porto/7.0.0/demo-real-estate.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 23 Apr 2019 15:01:39 GMT -->
</html>

resources/views/front/inc/header.blade.php
<!DOCTYPE html>
<html data-style-switcher-options="{'changeLogo': false, 'borderRadius': 0, 'colorPrimary': '#333b48', 'colorSecondary': '#219cd2', 'colorTertiary': '#2bca6e', 'colorQuaternary': '#FFF'}">
	
<!-- Mirrored from preview.oklerthemes.com/porto/7.0.0/demo-real-estate.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 23 Apr 2019 15:00:59 GMT -->
<head>

		<!-- Basic -->
		<meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">	
        
        <meta name="csrf-token" content="{{ csrf_token() }}">


		<title>Porto - Responsive HTML5 Template 7.0.0</title>	

		<meta name="keywords" content="HTML5 Template" />
		<meta name="description" content="Porto - Responsive HTML5 Template">
		<meta name="author" content="okler.net">

		<!-- Favicon -->
		<link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" />
		<link rel="apple-touch-icon" href="img/apple-touch-icon.png">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">

		<!-- Web Fonts  -->
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="{{ furl() }}/assets/vendor/bootstrap/css/bootstrap.min.css">
		<link rel="stylesheet" href="{{ furl() }}/assets/vendor/fontawesome-free/css/all.min.css">
		<link rel="stylesheet" href="{{ furl() }}/assets/vendor/animate/animate.min.css">
		<link rel="stylesheet" href="{{ furl() }}/assets/vendor/simple-line-icons/css/simple-line-icons.min.css">
		<link rel="stylesheet" href="{{ furl() }}/assets/vendor/owl.carousel/assets/owl.carousel.min.css">
		<link rel="stylesheet" href="{{ furl() }}/assets/vendor/owl.carousel/assets/owl.theme.default.min.css">
		<link rel="stylesheet" href="{{ furl() }}/assets/vendor/magnific-popup/magnific-popup.min.css">



		<!-- Theme CSS -->
		<link rel="stylesheet" href="{{ furl() }}/assets/css/theme.css">
		<link rel="stylesheet" href="{{ furl() }}/assets/css/theme-elements.css">
		<link rel="stylesheet" href="{{ furl() }}/assets/css/theme-blog.css">
		<link rel="stylesheet" href="{{ furl() }}/assets/css/theme-shop.css">

		<!-- Current Page CSS -->
		<link rel="stylesheet" href="{{ furl() }}/assets/vendor/rs-plugin/css/settings.css">
		<link rel="stylesheet" href="{{ furl() }}/assets/vendor/rs-plugin/css/layers.css">
		<link rel="stylesheet" href="{{ furl() }}/assets/vendor/rs-plugin/css/navigation.css">
		
		<!-- Demo CSS -->
		<link rel="stylesheet" href="{{ furl() }}/assets/css/demos/demo-real-estate.css">

		<!-- Skin CSS -->
        <link rel="stylesheet" href="{{ furl() }}/assets/css/skins/skin-real-estate.css">		
        <script src="{{ furl() }}/assets/master/style-switcher/style.switcher.localstorage.js"></script> 

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="{{ furl() }}/assets/css/custom.css">

		<!-- Head Libs -->
		<script src="{{ furl() }}/assets/vendor/modernizr/modernizr.min.js"></script>

	</head>
	<body class="loading-overlay-showing" data-loading-overlay>
		<div class="loading-overlay">
			<div class="bounce-loader">
				<div class="bounce1"></div>
				<div class="bounce2"></div>
				<div class="bounce3"></div>
			</div>
        </div>
        
        <div class="body">
            @include('front.inc.header.nav')

            <div role="main" class="main">