routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Front')->name('front.')->group(function()
{
	Route::get('/','HomeController@index')->name('get.home.index');
	Route::post('/loadMore','HomeController@loadMore')->name('get.home.loadMore');

	Route::get('/properties','PropertyController@index')->name('get.property.index');
	Route::get('/properties/sell','PropertyController@sell')->name('get.property.sell');
	Route::get('/properties/rent','PropertyController@rent')->name('get.property.rent');
	Route::get('/properties/place/{slug}','PropertyController@place')->name('get.property.place');
	
	Route::post('/properties/search','PropertyController@doSearch')->name('post.property.doSearch');
	Route::get('/properties/{slug}','PropertyController@show')->name('get.property.show');

	Route::get('/agents','AgentController@index')->name('get.agent.index');
	Route::get('/agents/profile/{slug}','AgentController@profile')->name('get.agent.profile');
	Route::post('/agents/message','AgentController@sendMessage')->name('post.agent.sendMessage');

	Route::get('/about', 'AboutController@index')->name('get.about.index');

	Route::get('/contact', 'ContactController@index')->name('get.contact.index');
	Route::post('/contact', 'ContactController@sendMessage')->name('post.contact.sendMessage');

	Route::post('/subscribe', 'HomeController@subscribe')->name('post.home.subscribe');
});

app/Http/Controllers/Front/AboutController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\About;
use App\Models\Agent;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AboutController extends Controller
{
    public function index()
    {
        $data['about'] = About::first();
        $data['agents'] = Agent::select('name', 'slug', 'img', 'email', 'phone')
        ->where('show_in_homepage', 'yes')
        ->get();        
        
        return view('front.about.index')->with($data);
    }
}

app/Http/Controllers/Front/AgentController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Agent;
use App\Models\AgentRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\AgentRequestRequest;

class AgentController extends Controller
{
    public function index()
    {
        $data['agents'] = Agent::select('name', 'slug', 'pos', 'small_desc', 'img', 'email', 'phone', 'facebook', 'linkedin')
        ->where('show', 'yes')
        ->get();
        
        return view('front.agents.index')->with($data);
    }

    public function profile($slug)
    {
        $data['agent'] = Agent::where('slug', $slug)->first();

        return view('front.agents.profile')->with($data);
    }

    public function sendMessage(AgentRequestRequest $request)
    {
        if($request->ajax())
        {
            $data = $request->validated();
            AgentRequest::create($data);
            $message['success'] = trans('Message sent successfully');
            return response()->json($message);
        }
    }
}

app/Http/Controllers/Front/ContactController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Message;
use App\Models\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\MessageRequest;

class ContactController extends Controller
{
    public function index()
    {
        $data['contacts'] = Setting::select('email', 'mobile', 'linkedin', 'facebook', 'business_hours')
        ->first();
        return view('front.contact.index')->with($data);
    }

    public function sendMessage(MessageRequest $request)
    {
        if($request->ajax())
        {
            $data = $request->validated();
            Message::create($data);
            $message['success'] = trans('Message sent successfully');
            return response()->json($message);
        }
    }
}

app/Http/Controllers/Front/HomeController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Requests\SubscribeRequest;
use App\Http\Requests\LoadMoreRequest;
use App\Http\Controllers\Controller;
use App\Models\Slider;
use App\Models\Place;
use App\Models\Agent;
use App\Models\Prop;
use App\Models\Setting;
use App\Models\Subscribe;
use App\Models\Offer;
use View;

class HomeController extends Controller
{
    public function index()
    {
        $data['sliders'] = Slider::select('name', 'img', 'price', 'link')
        ->where('show', 'yes')
        ->get();

        $data['offers'] = Offer::select('name', 'sub_title', 'img', 'link')
        ->where('show_in_homepage', 'yes')
        ->get();

        $data['agents'] = Agent::select('name', 'slug', 'img', 'email', 'phone')
        ->where('show_in_homepage', 'yes')
        ->get();

        $data['places'] = Place::select('id', 'name', 'img', 'slug')
        ->where('show_in_homepage', 'yes')
        ->limit(6)
        ->get();

        $data['props'] = Prop::select('type', 'price', 'place_id', 'img', 'slug', 'beds', 'baths', 'lot_size')
        ->where('show_in_homepage', 'yes')
        ->limit(9)
        ->get();

        return view('front.index')->with($data);
    }

    public function loadMore(LoadMoreRequest $request)
    {
        if($request->ajax())
        {
            $data = $request->validated();

            if($data['num'] == 3) 
            {
                $data['props_two'] = Prop::select('type', 'price', 'place_id', 'img', 'slug', 'beds', 'baths', 'lot_size')
                ->where('show_in_homepage', 'yes')->skip(3)->take(3)->get();
                
                $view = View::make('front.render.propTwo', $data);
            }
            else if($data['num'] == 6) 
            {
                $data['props_three'] = Prop::select('type', 'price', 'place_id', 'img', 'slug', 'beds', 'baths', 'lot_size')
                ->where('show_in_homepage', 'yes')->skip(6)->take(3)->get();
                
                $view = View::make('front.render.propThree', $data);
            }
            

            $html = $view->render();
            
            return response()->json($html);
        }
    }

    public function subscribe(SubscribeRequest $request)
    {
        if($request->ajax())
        {
            $data = $request->validated();
            Subscribe::create($data);
            $message['success'] = trans('Subscribed successfully');
            return response()->json($message);
        }
    }
}

app/Http/Controllers/Front/PropertyController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Prop;
use App\Models\Agent;
use App\Models\Place;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\SearchRequest;

class PropertyController extends Controller
{
    public function index(SearchRequest $request)
    {
        $params = $request->validated();

        if($params !== [])
        {
            $data['status'] = 'search';
            $data['search'] = true;
            $data['params'] = $params;

            $props = Prop::when($params['cat'] !== null, function ($props) {
                    return $props->where('category_id', request('cat'));
                })
                ->when($params['place'] !== null, function ($props) {
                    return $props->where('place_id', request('place'));
                })
                ->when($params['type'] !== null, function ($props) {
                    return $props->where('type', request('type'));
                })
                ->when($params['min_price'] !== null, function ($props) {
                    return $props->where('price', '>=', request('min_price'));
                })
                ->when($params['max_price'] !== null, function ($props) {
                    return $props->where('price', '<=', request('max_price'));
                });

            $data['props'] = $props->paginate(6);
        } else {
            $data['status'] = 'all';
            $data['props'] = Prop::paginate(6);
        }

        
        return view('front.properties.index')->with($data);
    }

    public function sell()
    {
        $data['props'] = Prop::where('type', 'sell')->paginate(6);
        $data['count'] = count(Prop::where('type', 'sell')->get());
        $data['status'] = 'sell';

        return view('front.properties.index')->with($data);
    }

    public function rent()
    {
        $data['props'] = Prop::where('type', 'rent')->paginate(6);
        $data['count'] = count(Prop::where('type', 'rent')->get());
        $data['status'] = 'rent';

        return view('front.properties.index')->with($data);
    }

    public function place($slug)
    {
        $place = Place::where('slug', $slug)->first();
        $data['place'] = $place;
        $data['props'] = Prop::where('place_id', $place->id)->paginate(6);
        $data['count'] = count(Prop::where('type', 'rent')->get());
        $data['status'] = 'place';

        return view('front.properties.index')->with($data);
    }


    public function show($slug)
    {
        $data['prop'] = Prop::where('slug', $slug)->first();
        return view('front.properties.show')->with($data);
    }
}

resources/views/front/contact/index.blade.php
@extends('front.main')


@section('content')
  <section class="page-header page-header-modern bg-color-light-scale-1 page-header-md">
    <div class="container">
      <div class="row">
        <div class="col-md-8 order-2 order-md-1 align-self-center p-static">
          <h1 class="text-dark">Contact</h1>
        </div>
        <div class="col-md-4 order-1 order-md-2 align-self-center">
          <ul class="breadcrumb d-block text-md-right">
            <li><a href="{{ route('front.get.home.index') }}">Home</a></li>
            <li class="active">Contact</li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <div class="container">

    @include('_messages')

    <div class="row">
      <div class="col-lg-8">

        <h4 class="text-primary mt-4">Send a Message</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur eget leo at velit imperdiet varius. In eu ipsum vitae velit congue iaculis vitae at risus.</p>

        @include('front.errors.error')

        <form id="contactForm" class="contact-form" method="POST">
          @csrf
          <div class="form-row">
            <div class="form-group col-lg-6">
              <label>Your name *</label>
              <input type="text" minlength="5" maxlength="30" class="form-control" name="name" id="name" required>
            </div>
            <div class="form-group col-lg-6">
              <label>Your email address *</label>
              <input type="email" minlength="5" maxlength="50" class="form-control" name="email" id="email" required>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col">
              <label>Message *</label>
              <textarea maxlength="5000" rows="5" class="form-control" name="message" id="message" required></textarea>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col">
              <input type="submit" value="Send Message" class="btn btn-secondary mb-4" data-loading-text="Loading...">
            </div>
          </div>
        </form>
</div>
      <div class="col-lg-4">
        <div class="row">
          <div class="col-md-6 col-lg-12 mt-lg-4 order-1">
            <h4 class="text-primary">The Office</h4>
            <ul class="list list-icons mt-3">
              <li>
                <a href="mailto:mail@domain.com">
                  <i class="icon-envelope-open icons"></i> {{ $contacts->email }}
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="icon-call-out icons"></i> {{ $contacts->mobile }}
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="icon-social-linkedin icons"></i> {{ $contacts->linkedin }}
                </a>
              </li>
              <li>
                <a href="#">
                  <i class="icon-social-facebook icons"></i> {{ $contacts->facebook }}
                </a>
              </li>
            </ul>
          </div>
          <div class="col order-2 order-md-3 order-lg-2">
            <hr class="solid">
          </div>
          <div class="col-md-6 col-lg-12 order-3 order-md-2 order-lg-3">
            <h4 class="text-primary">Business Hours</h4>
            <ul class="list list-icons mt-3">
              <li><i class="far fa-clock"></i> {{ $contacts->business_hours }}</li>
            </ul>
          </div>
        </div>
      </div>

    </div>

  </div>

  <!-- Google Maps - Go to the bottom of the page to change settings and map location. -->
  <div id="googlemaps" class="google-map mt-5 mb-0"></div>

@endsection

@section('scripts')
<script>
  $('#nav-contact').addClass('active');

  $('#contactForm').submit(function(e){
        e.preventDefault();
        $('#display-errors').hide()
        $('#display-errors ul').empty()
        var formData  = new FormData(jQuery(this)[0]);
        axios.post('{{ route('front.post.contact.sendMessage') }}', {
            name: formData.get('name'),
            email: formData.get('email'),
            message: formData.get('message') 
        })
        .then(function (res) {
            Swal.fire(
              'Success!',
              res.data.success,
              'success'
            )

            $('#contactForm').trigger('reset')
        })
        .catch(function (res) {
          let errors = res.response.data.errors
            $('#display-errors').show()
            for (var error in errors) {
                $('#display-errors ul').append('<li class="text-center">'+ errors[error] +'</li>')
            }
        });

  })

</script>
@endsection