routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Front')->name('front.')->group(function()
{
	Route::get('/','HomeController@index')->name('get.home.index');
	Route::post('/loadMore','HomeController@loadMore')->name('get.home.loadMore');

	Route::get('/properties','PropertyController@index')->name('get.property.index');
	Route::get('/properties/sell','PropertyController@sell')->name('get.property.sell');
	Route::get('/properties/rent','PropertyController@rent')->name('get.property.rent');
	Route::get('/properties/place/{slug}','PropertyController@place')->name('get.property.place');
	
	Route::post('/properties/search','PropertyController@doSearch')->name('post.property.doSearch');
	Route::get('/properties/{slug}','PropertyController@show')->name('get.property.show');

	Route::get('/agents','AgentController@index')->name('get.agent.index');
	Route::get('/agents/profile/{slug}','AgentController@profile')->name('get.agent.profile');
	Route::post('/agents/message','AgentController@sendMessage')->name('post.agent.sendMessage');

	Route::get('/about', 'AboutController@index')->name('get.about.index');

	Route::get('/contact', 'ContactController@index')->name('get.contact.index');
	Route::post('/contact', 'ContactController@sendMessage')->name('post.contact.sendMessage');

	Route::post('/subscribe', 'HomeController@subscribe')->name('post.home.subscribe');
});

app/Http/Controllers/Front/AboutController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\About;
use App\Models\Agent;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AboutController extends Controller
{
    public function index()
    {
        $data['about'] = About::first();
        $data['agents'] = Agent::select('name', 'slug', 'img', 'email', 'phone')
        ->where('show_in_homepage', 'yes')
        ->get();        
        
        return view('front.about.index')->with($data);
    }
}

app/Http/Controllers/Front/AgentController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Agent;
use App\Models\AgentRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\AgentRequestRequest;

class AgentController extends Controller
{
    public function index()
    {
        $data['agents'] = Agent::select('name', 'slug', 'pos', 'small_desc', 'img', 'email', 'phone', 'facebook', 'linkedin')
        ->where('show', 'yes')
        ->get();
        
        return view('front.agents.index')->with($data);
    }

    public function profile($slug)
    {
        $data['agent'] = Agent::where('slug', $slug)->first();

        return view('front.agents.profile')->with($data);
    }

    public function sendMessage(AgentRequestRequest $request)
    {
        if($request->ajax())
        {
            $data = $request->validated();
            AgentRequest::create($data);
            $message['success'] = trans('Message sent successfully');
            return response()->json($message);
        }
    }
}

app/Http/Controllers/Front/ContactController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Message;
use App\Models\Setting;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\MessageRequest;

class ContactController extends Controller
{
    public function index()
    {
        $data['contacts'] = Setting::select('email', 'mobile', 'linkedin', 'facebook', 'business_hours')
        ->first();
        return view('front.contact.index')->with($data);
    }

    public function sendMessage(MessageRequest $request)
    {
        if($request->ajax())
        {
            $data = $request->validated();
            Message::create($data);
            $message['success'] = trans('Message sent successfully');
            return response()->json($message);
        }
    }
}

app/Http/Controllers/Front/HomeController.php
<?php

namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Requests\SubscribeRequest;
use App\Http\Requests\LoadMoreRequest;
use App\Http\Controllers\Controller;
use App\Models\Slider;
use App\Models\Place;
use App\Models\Agent;
use App\Models\Prop;
use App\Models\Setting;
use App\Models\Subscribe;
use App\Models\Offer;
use View;

class HomeController extends Controller
{
    public function index()
    {
        $data['sliders'] = Slider::select('name', 'img', 'price', 'link')
        ->where('show', 'yes')
        ->get();

        $data['offers'] = Offer::select('name', 'sub_title', 'img', 'link')
        ->where('show_in_homepage', 'yes')
        ->get();

        $data['agents'] = Agent::select('name', 'slug', 'img', 'email', 'phone')
        ->where('show_in_homepage', 'yes')
        ->get();

        $data['places'] = Place::select('id', 'name', 'img', 'slug')
        ->where('show_in_homepage', 'yes')
        ->limit(6)
        ->get();

        $data['props'] = Prop::select('type', 'price', 'place_id', 'img', 'slug', 'beds', 'baths', 'lot_size')
        ->where('show_in_homepage', 'yes')
        ->limit(9)
        ->get();

        return view('front.index')->with($data);
    }

    public function loadMore(LoadMoreRequest $request)
    {
        if($request->ajax())
        {
            $data = $request->validated();

            if($data['num'] == 3) 
            {
                $data['props_two'] = Prop::select('type', 'price', 'place_id', 'img', 'slug', 'beds', 'baths', 'lot_size')
                ->where('show_in_homepage', 'yes')->skip(3)->take(3)->get();
                
                $view = View::make('front.render.propTwo', $data);
            }
            else if($data['num'] == 6) 
            {
                $data['props_three'] = Prop::select('type', 'price', 'place_id', 'img', 'slug', 'beds', 'baths', 'lot_size')
                ->where('show_in_homepage', 'yes')->skip(6)->take(3)->get();
                
                $view = View::make('front.render.propThree', $data);
            }
            

            $html = $view->render();
            
            return response()->json($html);
        }
    }

    public function subscribe(SubscribeRequest $request)
    {
        if($request->ajax())
        {
            $data = $request->validated();
            Subscribe::create($data);
            $message['success'] = trans('Subscribed successfully');
            return response()->json($message);
        }
    }
}

app/Http/Controllers/Front/PropertyController.php
<?php

namespace App\Http\Controllers\Front;

use App\Models\Prop;
use App\Models\Agent;
use App\Models\Place;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\SearchRequest;

class PropertyController extends Controller
{
    public function index(SearchRequest $request)
    {
        $params = $request->validated();

        if($params !== [])
        {
            $data['status'] = 'search';
            $data['search'] = true;
            $data['params'] = $params;

            $props = Prop::when($params['cat'] !== null, function ($props) {
                    return $props->where('category_id', request('cat'));
                })
                ->when($params['place'] !== null, function ($props) {
                    return $props->where('place_id', request('place'));
                })
                ->when($params['type'] !== null, function ($props) {
                    return $props->where('type', request('type'));
                })
                ->when($params['min_price'] !== null, function ($props) {
                    return $props->where('price', '>=', request('min_price'));
                })
                ->when($params['max_price'] !== null, function ($props) {
                    return $props->where('price', '<=', request('max_price'));
                });

            $data['props'] = $props->paginate(6);
        } else {
            $data['status'] = 'all';
            $data['props'] = Prop::paginate(6);
        }

        
        return view('front.properties.index')->with($data);
    }

    public function sell()
    {
        $data['props'] = Prop::where('type', 'sell')->paginate(6);
        $data['count'] = count(Prop::where('type', 'sell')->get());
        $data['status'] = 'sell';

        return view('front.properties.index')->with($data);
    }

    public function rent()
    {
        $data['props'] = Prop::where('type', 'rent')->paginate(6);
        $data['count'] = count(Prop::where('type', 'rent')->get());
        $data['status'] = 'rent';

        return view('front.properties.index')->with($data);
    }

    public function place($slug)
    {
        $place = Place::where('slug', $slug)->first();
        $data['place'] = $place;
        $data['props'] = Prop::where('place_id', $place->id)->paginate(6);
        $data['count'] = count(Prop::where('type', 'rent')->get());
        $data['status'] = 'place';

        return view('front.properties.index')->with($data);
    }


    public function show($slug)
    {
        $data['prop'] = Prop::where('slug', $slug)->first();
        return view('front.properties.show')->with($data);
    }
}

resources/views/front/properties/search.blade.php
@extends('front.main')


@section('content')
<section class="page-header page-header-modern bg-color-light-scale-1 page-header-md">
  <div class="container">
    <div class="row">
      <div class="col-md-8 order-2 order-md-1 align-self-center p-static">
        <h1 class="text-dark">Properties <p class="lead mb-0">
          Listings for 
          @if($status == 'all')
           Sell or Rent 
          @elseif($status == 'sell') 
            Sell 
          @elseif($status == 'rent')  
            Rent 
          @else 
            Search results
          @endif - {{ $count }} properties
        </p></h1>
      </div>
      <div class="col-md-4 order-1 order-md-2 align-self-center">
        <ul class="breadcrumb d-block text-md-right">
          <li><a href="{{ route('front.get.home.index') }}">Home</a></li>
          <li class="active">PROPERTIES</li>
        </ul>
      </div>
    </div>
    <div class="row mt-4">
      <div class="col">
        <form id="propertiesForm" action="{{ route('front.post.property.doSearch') }}" method="POST">
          @csrf
          <div class="form-row">
            <div class="form-group col-lg-2 mb-0">
              <div class="form-control-custom mb-3">
                <select class="form-control text-uppercase text-2" name="cat" data-msg-required="This field is required."
                  id="propertiesPropertyType2" >
                  <option value="">Category</option>
                  @foreach ($cats as $cat)  
                    <option value="{{ $cat->id }}" @if($params['cat'] == $cat->id) selected @endif>{{ $cat->name }}</option>
                  @endforeach
                </select>
              </div>
            </div>
            
            <div class="form-group col-lg-2 mb-0">
              <div class="form-control-custom mb-3">
                <select class="form-control text-uppercase text-2" name="place" data-msg-required="This field is required."
                  id="propertiesLocation2" >
                  <option value="">Place</option>
                  @foreach ($places as $place)  
                    <option value="{{ $place->id }}" @isset($params) @if($params['place'] == $place->id) selected @endif @endisset>{{ $place->name }}</option>
                  @endforeach
                </select>
              </div>
            </div>

            <div class="form-group col-lg-2 mb-0">
              <div class="form-control-custom mb-3">
                <select class="form-control text-uppercase text-2" name="type" data-msg-required="This field is required."
                  id="propertiesType2" >
                  <option value="">Type</option>
                  <option value="sell" @isset($params) @if($params['type'] == 'sell') selected @endif @endisset>sell</option>
                  <option value="rent" @isset($params) @if($params['type'] == 'rent') selected @endif @endisset>rent</option>
                </select>
              </div>
            </div>

            <div class="form-group col-lg-2 mb-0">
              <div class="form-control-custom mb-3">
                <input class="form-control text-uppercase text-2" name="min_price" placeholder="Min Price" @isset($params) value="{{ $params['min_price'] }}" @endisset>
              </div>
            </div>

            <div class="form-group col-lg-2 mb-0">
              <div class="form-control-custom mb-3">
                <input class="form-control text-uppercase text-2" name="max_price" placeholder="Max Price" @isset($params) value="{{ $params['max_price'] }}" @endisset>
              </div>
            </div>

            <div class="form-group col-lg-1 mb-0">
              <input type="submit" value="Search" class="btn btn-secondary btn-lg btn-block text-uppercase text-2">
            </div>
            <div class="col-lg-1 mb-0">
              <a type="button" href="{{ route('front.get.property.index') }}" style="color: white" class="btn btn-info btn-lg btn-block text-uppercase text-2">
                Refresh
              </a> 
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

<div class="container">

  <div class="row mb-4 properties-listing sort-destination p-0">

    @if($count == 0)
      <div class="col-md-4 offset-md-4 mt-5 mb-5 isotope-item">
        <div class="text-center">
          <strong>No results for this options</strong>
        </div>
      </div>
    @endif

    @foreach ($props as $prop)
    <div class="col-md-6 col-lg-4 p-3 isotope-item">
        <div class="listing-item">
          <a href="{{ route('front.get.property.show', ['slug' => $prop->slug]) }}" class="text-decoration-none">
            <div class="thumb-info thumb-info-lighten border">
              <div class="thumb-info-wrapper m-0">
                <img src="{{ getImage(PROPS_PATH, $prop->img) }}" class="img-fluid" alt="">
                <div class="thumb-info-listing-type bg-color-secondary text-uppercase text-color-light font-weight-semibold p-1 pl-3 pr-3">
                  for {{ $prop->type }}
                </div>
              </div>
              <div class="thumb-info-price bg-color-primary text-color-light text-4 p-2 pl-4 pr-4">
                @if($prop->type == 'sell')
                  $ {{ number_format($prop->price) }}
                @else 
                  $ {{ number_format($prop->price) }} / month
                @endif
                <i class="fas fa-caret-right text-color-secondary float-right"></i>
              </div>
              <div class="custom-thumb-info-title b-normal p-4">
                <div class="thumb-info-inner text-3">{{ $prop->place->name }}</div>
                <ul class="accommodations text-uppercase font-weight-bold p-0 mb-0 text-2">
                  <li>
                    <span class="accomodation-title">
                      Beds:
                    </span>
                    <span class="accomodation-value custom-color-1">
                      {{ $prop->beds }}
                    </span>
                  </li>
                  <li>
                    <span class="accomodation-title">
                      Baths:
                    </span>
                    <span class="accomodation-value custom-color-1">
                        {{ $prop->baths }}                      
                    </span>
                  </li>
                  <li>
                    <span class="accomodation-title">
                      Sq Ft:
                    </span>
                    <span class="accomodation-value custom-color-1">
                        {{ $prop->lot_size }}
                    </span>
                  </li>
                </ul>
              </div>
            </div>
          </a>
        </div>
      </div>        
    @endforeach
  
  </div>

  <div class="pagination justify-content-center">
    {{ $props->render() }}
  </div>

</div>
@endsection

@section('scripts')
<script>
    $('#nav-props').addClass('active');

</script>
@endsection

resources/views/front/properties/show.blade.php
@extends('front.main')


@section('content')
  <section class="page-header page-header-modern bg-color-light-scale-1 page-header-md">
    <div class="container">
      <div class="row">
        <div class="col-md-8 order-2 order-md-1 align-self-center p-static">
            <h1 class="text-dark">{{ $prop->name }}<p class="lead mb-0">{{ $prop->place->name }} - <a href="#map" data-hash data-hash-offset="100">(Map Location)</a></p></h1>
        </div>
        <div class="col-md-4 order-1 order-md-2 align-self-center">
          <ul class="breadcrumb d-block text-md-right">
            <li><a href="{{ route('front.get.home.index') }}">Home</a></li>
            <li><a href="{{ route('front.get.property.index') }}">Properties</a></li>
            <li class="active">Detail</li>
          </ul>
        </div>
      </div>
    </div>
  </section>

  <div class="container">

    <div class="row pb-5 pt-3">
      <div class="col-lg-9">
            
        <div class="row">
          <div class="col-lg-7">

            <span class="thumb-info-listing-type thumb-info-listing-type-detail bg-color-secondary text-uppercase text-color-light font-weight-semibold p-2 pl-3 pr-3">
              for {{ $prop->type }}
            </span>

            <div class="thumb-gallery">
              <div class="lightbox" data-plugin-options="{'delegate': 'a', 'type': 'image', 'gallery': {'enabled': true}}">
                <div class="owl-carousel owl-theme manual thumb-gallery-detail show-nav-hover" id="thumbGalleryDetail">
                  @foreach ($prop->images as $image)                      
                    <div>
                      <a href="img/demos/real-estate/listings/listing-detail-1.jpg">
                        <span class="thumb-info thumb-info-centered-info thumb-info-no-borders text-4">
                          <span class="thumb-info-wrapper text-4">
                            <img alt="Property Detail" src="{{ getMediumImage(PROPS_PATH, $image->image) }}" class="img-fluid">
                            <span class="thumb-info-title text-4">
                              <span class="thumb-info-inner text-4"><i class="icon-magnifier icons text-4"></i></span>
                            </span>
                          </span>
                        </span>
                      </a>
                    </div>
                  @endforeach
                </div>
              </div>

              <div class="owl-carousel owl-theme manual thumb-gallery-thumbs mt" id="thumbGalleryThumbs">
                @foreach ($prop->images as $image)                                      
                  <div>
                    <img alt="Property Detail" src="{{ getSmallImage(PROPS_PATH, $image->image) }}" class="img-fluid cur-pointer">
                  </div>
                @endforeach
              </div>
            </div>

          </div>
          <div class="col-lg-5">
            
            <table class="table table-striped">
              <colgroup>
                <col width="35%">
                <col width="65%">
              </colgroup>
              <tbody>
                <tr>
                  <td class="bg-color-primary text-light align-middle">
                    Price
                  </td>
                  <td class="text-4 font-weight-bold align-middle bg-color-primary text-light">
                    @if($prop->type == 'sell')
                      $ {{ number_format($prop->price) }}
                    @else 
                      $ {{ number_format($prop->price) }} / month
                    @endif
                  </td>
                </tr>
                <tr>
                  <td>
                    Listing ID
                  </td>
                  <td>
                    {{ $prop->code }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Address
                  </td>
                  <td>
                    {{ $prop->address }}<br><a href="#map" class="text-2" data-hash data-hash-offset="100">(Map Location)</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    Neighborhood
                  </td>
                  <td>
                    {{ $prop->neighborhood }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Beds
                  </td>
                  <td>
                    {{ $prop->beds }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Baths
                  </td>
                  <td>
                    {{ $prop->baths }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Garages
                  </td>
                  <td>
                      {{ $prop->garages }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Living Area
                  </td>
                  <td>
                      {{ number_format($prop->living_area) }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Lot Size
                  </td>
                  <td>
                      {{ number_format($prop->lot_size) }}
                  </td>
                </tr>
                <tr>
                  <td>
                    Year Built
                  </td>
                  <td>
                      {{ $prop->year_built }}
                  </td>
                </tr>
              </tbody>
            </table>

          </div>
        </div>

        <div class="row">
          <div class="col">

            <h4 class="mt-3 mb-3">Description</h4>
            <p>{!! $prop->desc !!}</p>

            <hr class="solid my-5">

            <h4 class="mt-3 mb-3">Features</h4>

            <ul class="list list-icons list-secondary row m-0">
              @foreach ($prop->features as $feature)                  
                <li class="col-sm-6 col-lg-4"><i class="fas fa-check"></i> {{ $feature->name }}</li>
              @endforeach
            </ul>

            <hr class="solid my-5">

            <h4 class="mt-3 mb-3" id="map">Map Location</h4>
            <div id="googlemaps" class="google-map mb-0"></div>

          </div>
        </div>

      </div>
      <div class="col-lg-3">
        <aside class="sidebar">
          <div class="agents text-color-light text-center pb-3">
            <h4 class="text-light pt-5 m-0">Property Agents</h4>
            <div class="owl-carousel owl-theme nav-bottom rounded-nav pl-1 pr-1 pt-3 m-0" data-plugin-options="{'items': 1, 'loop': false, 'dots': false, 'nav': true}">
              @foreach ($prop->agents as $agent)                  
                <div class="pr-2 pl-2">
                  <a href="{{ route('front.get.agent.profile', ['slug' => $agent->slug]) }}" class="text-decoration-none">
                    <span class="agent-thumb">
                      <img class="img-fluid rounded-circle" src="{{ getSmallImage(AGENTS_PATH, $agent->img) }}" alt />
                    </span>
                    <span class="agent-infos text-light pt-3">
                      <strong class="text-uppercase font-weight-bold">{{ $agent->name }}</strong>
                      <span class="font-weight-light">{{ $agent->phone }}</span>
                      <span class="font-weight-light">{{ $agent->email }}</span>
                    </span>
                  </a>
                </div>
              @endforeach
            </div>
          </div>

          <h4 class="pt-4 mb-3 text-color-dark">Request Information</h4>
          <p>Contact us or give us a call to request more information</p>

          @include('front.errors.error')

          <form id="contactAgentForm" class="contact-form mb-4" method="POST">
            @csrf
            <input type="hidden" name="id" value="{{ $agent->id }}">

            <div class="form-row">
              <div class="form-group col">
                <label>Your name *</label>
                <input type="text" value="" minlength="5" maxlength="30" class="form-control" name="name" id="name" required>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col">
                <label>Your email address *</label>
                <input type="email" value="" data-msg-required="Please enter your email address." minlength="5" maxlength="50" class="form-control" name="email" id="email" required>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col">
                <label>Subject</label>
                <input type="text" value="" maxlength="100" class="form-control" name="subject" id="subject">
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col">
                <label>Message *</label>
                <textarea maxlength="5000" rows="6" class="form-control" name="message" id="message" required></textarea>
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col">
                <input type="submit" value="Send Message" class="btn btn-secondary mb-lg-5">
              </div>
            </div>
          </form>

        </aside>
      </div>
    </div>

  </div>
@endsection

@section('scripts')
<script>
    $('#nav-props').addClass('active');

    $('#contactAgentForm').submit(function(e){
        e.preventDefault();
        $('#display-errors').hide()
        $('#display-errors ul').empty()
        var formData  = new FormData(jQuery(this)[0]);

        axios.post('{{ route('front.post.agent.sendMessage') }}', {
            agent_id: formData.get('id'),
            name: formData.get('name'),
            email: formData.get('email'),
            subject: formData.get('subject'),
            message: formData.get('message') 
        })
        .then(function (res) {
            Swal.fire(
              'Success!',
              res.data.success,
              'success'
            )

            $('#contactAgentForm').trigger('reset')
        })
        .catch(function (res) {
          let errors = res.response.data.errors
            $('#display-errors').show()
            for (var error in errors) {
                $('#display-errors ul').append('<li class="text-center">'+ errors[error] +'</li>')
            }
        });

  })

</script>
@endsection